name: Publish

on:
  push:
    branches: ["master"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      KO_DEFAULTPLATFORMS: "linux/arm64,linux/amd64"
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v2
      - uses: ko-build/setup-ko@v0.6
      - run: ko build --bare
